### ISSUE TITLE
Lab Report 3 Feedback

### ISSUE THREAD

**Issue by farnaf** [kkbunny247/cse15l-lab-reports#3]
Here is your feedback for Lab Report 3 - Streamlining `ssh` Configuration:

- [x] Show your `.ssh/config` file, and how you edited it (with VScode, another program, etc)
- [x] Show the `ssh` command logging you into your account using just the alias you chose.
- [ ] Show an `scp` command copying a file to your account using just the alias you chose.

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by kkbunny247** [comment]
Sorry! I didn't see that we had to show an scp command as well since I was looking at the instructions for Group Choice 1 on the Week 5 page. 

Here is my revised Lab Report 3:

https://github.com/kkbunny247/cse15l-lab-reports
https://kkbunny247.github.io/cse15l-lab-reports/
https://kkbunny247.github.io/cse15l-lab-reports/lab-report-3-week-6.html
(this was also published as a regrade request on Gradescope)
